#!/bin/bash
#
# Backup /home to gdrive
# Executed by anacron every week
rclone -v -L sync ~ remote: --exclude "Downloads/**" \
                            --exclude ".*{/**,}" \
                            --exclude "Music/**"

