#!/bin/bash
#
# List all user-installed packages on a debian system

logfile="/var/log/apt/history.log"
logs="zcat $logfile.*.gz | cat - $logfile"
regex="^Commandline: (apt|apt-get) +install +\K( *(\w+-?)+)+"
apps=$(eval $logs | grep -oP "$regex" | tr -s ' ' '\n' | sort -u)

for app in $apps;
do
	# check if a package is installed
	grep-status -PX $app &>/dev/null
	if [[ $? -eq 0 ]]; then
		echo $app
	fi
done

