#!/bin/bash

# Lists all user-installed programs

logfile="/var/log/apt/history.log"
logs="zcat $logfile.*.gz | cat - $logfile"
regex="^Commandline: (apt|apt-get) +install +\K(\w+-)*\w+( ((\w+-)*\w+))*"
apps=$(eval $logs | grep -Po "$regex" | tr ' ' '\n' | sort -u)

for app in $apps;
do
	# check if a program is installed
	dpkg-query -s $app &>/dev/null
	if [ $? -eq 0 ]; then
		echo $app
	fi
done

