#!/bin/bash
#
# Display total mp3 duration of a folder

duration=0
while read -d $'\0' song; do
    (( duration += $(mp3info -p "%S\n" "$song") ))
done < <(find "$1" -type f -print0)

date +%T -d "1970-01-01 + ${duration} seconds"

