#!/bin/bash

# List all online players from UrT DN server
URL=https://drunknoobs.com/server/eagle-24-7

wget -qO- $URL | tr -d '\n' | grep -oP 'config=0"> \K([^ ])+' \
               | perl -MHTML::Entities -pe 'decode_entities($_);'

