#!/bin/bash
#
# Toggle night mode in GNOME
# Binded to ctrl + alt + n

status=$(gsettings get org.gnome.settings-daemon.plugins.color night-light-enabled)

if [[ "$status" == "true" ]]; then
	gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
else
	gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
fi

