#!/bin/bash
#
# Display top 10 biggest files in the directory specified by the first argument
# If the argument is ommited, home directory is used instead.

[[ -n "$1" ]] && DIR="$1" || DIR="$HOME"

find "$DIR" -type f -print0 | xargs -0 du \
                            | sort -nr | head | cut -f2 \
                            | xargs -d '\n' du -sh
